export const types = {
    AGREGAR_PRODUCTO:'[Products] AGREGAR PRODUCTO',
    AGREGAR_PRODUCTO_EXITOSO:'[Products] AGREGAR PRODUCTO EXITOSO',
    AGREGAR_PRODUCTO_ERROR:'[Products] AGREGAR PRODUCTO ERROR'
}