export const types = {
    AGREGAR_PRODUCTO:'[Products] AGREGAR PRODUCTO',
    AGREGAR_PRODUCTO_EXITOSO:'[Products] AGREGAR PRODUCTO EXITOSO',
    AGREGAR_PRODUCTO_ERROR:'[Products] AGREGAR PRODUCTO ERROR',

    LISTADO_PRODUCTO:'[List] MOSTRAR LISTADO PRODUCTO',
    LISTADO_PRODUCTO_EXITOSO:'[List] LISTADO PRODUCTO EXITOSO',
    LISTADO_PRODUCTO_ERROR:'[List] LISTADO PRODUCTO ERROR',

    ELIMINAR_PRODUCTO:'[Product] ELIMINAR PRODUCTO',
    ELIMINAR_PRODUCTO_EXITOSO:'[Product] ELIMINAR PRODUCTO EXITOSO',
    ELIMINAR_PRODUCTO_ERROR:'[Product] ELIMINAR PRODUCTO ERROR'
}